name: Docker Image CI
on:
  push:
    branches:
      - main
    tags:
      - debug
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the Docker image"
        required: true
        default: debug
        type: choice
        options:
          - debug
          - stable
          - beta
          - nightly
          - latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Set Docker Tag
      id: set_tag
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          echo "TAG=latest" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        else
          echo "TAG=debug" >> $GITHUB_ENV
        fi

    - name: Create Buildx [multi-builder]
      run: docker buildx create --name="multi-builder" --platform="linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/386"

    - name: Build the Docker image
      run: docker buildx build \
        --push \
        --builder="multi-builder" \
        --platform="linux/amd64,linux/386,linux/arm64,linux/arm/v8,linux/arm/v7,linux/arm/v6,linux/ppc64le" \
        --tag="gegedesembri/telegram-bot-api:${TAG}" .
